{
 "title": "metrics",
 "tags": [
  "prometheus",
  "node",
  "misc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(host_load1{job=\"node\"}, instance)"
    }
   },
   {
    "name": "filesystem_mountpoint",
    "query": {
     "query": "query_result(host_filesystem_size{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(host_load1{job=\"node\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu)(host_cpu_seconds_total{job=\"node\", instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "host_memory_total_bytes{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "All Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(host_filesystem_total_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - host_boot_time{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(mode)(irate(host_cpu_seconds_total{job=\"node\", mode!=\"idle\"}[5m])) > 0",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "host_memory_buffers_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "host_memory_cached_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "host_memory_free_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "free"
    },
    {
     "expr": "host_memory_total_bytes{job=\"node\", instance=~\"$node:.*\"} - host_memory_free_bytes{job=\"node\", instance=~\"$node:.*\"} - host_memory_cached_bytes{job=\"node\", instance=~\"$node:.*\"} - host_memory_buffers_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Filesystem $filesystem_mountpoint usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(host_filesystem_used_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(host_filesystem_free_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(host_network_transmit_bytes_total{job=\"node\", instance=~\"$node:.*\", device=\"enp4s0\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(host_network_receive_bytes_total{job=\"node\", instance=~\"$node:.*\", device=\"enp4s0\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  }
 ]
}