[api]
  enabled = true

[sources.journald]
  type = "journald"

# Capture the metrics from the host.
[sources.host_metrics]
  type = "host_metrics"

# Emit internal Vector metrics.
[sources.internal_metrics]
  type = "internal_metrics"

[sinks.vector_aggregator]
  type = "vector"
  inputs = [ "journald" ]
  address = "127.0.0.1:6000"
  send_buffer_bytes = 65_536
  version = "1"

# Expose metrics for scraping in the Prometheus format.
[sinks.vector_metrics]
  type = "vector"
  inputs = ["internal_metrics", "host_metrics"]
  address = "127.0.0.1:6001"
  send_buffer_bytes = 65_536
  version = "1"



